[Feat/#11] 앱바 로직 페이지 내부로 옮기기
22nd-Hoondong/Re-Frame pull request #21
Opened 2023-11-23 08:28 UTC by ldh019

## 개요
페이지 별로 앱바 구성 요소를 설정할 수 있습니다.

## 작업사항
- App bar 설정을 위한 Mixin 생성
- 각 페이지 mixin 합성

## 변경된 부분
- 각 페이지에 Global key를 생성자로 주입

2023-11-23 08:36 UTC, hnnynh approved these changes
매번 Scaffold에서 AppBar를 만들지 않고도 params로 AppBar를 바꿔줄 수 있게됐네요! 굳굳

2023-11-23 08:40 UTC, coffeesigma approved these changes
화면마다 다른 Appbar 를 편하게 설정해주는건가요.. 신기방기

2023-11-23 08:49 UTC, falconlee236 requested changes
GlobalKEy를 사용한것은 생각하지도 못했네요...
좋은 코드 배워갑니다

가벼운 한가지 수정 사항만 바꿔주시면 될것 같아요

2023-11-23 08:49 UTC, falconlee236 commented on lib/Pages/gallery.dart
> +import '../main.dart';
여기만 단순 ../main.dart인것 같아서
여기만 package:re_frame/main.dart 로 바꾸면 더 보기 좋을것 같아요

2023-11-24 06:30 UTC, falconlee236 approved these changes
고생많으셨습니다!!

2023-11-24 06:31 UTC, merged