[FEAT] 페이지 뷰에 화면 전환 indicator추가
22nd-Hoondong/Re-Frame pull request #22
Opened 2023-11-25 06:47 UTC by falconlee236

## 개요
페이지 뷰에 화면 전환을 할때 확인하는 indicator를 추가했습니다.

## 작업사항
- smooth_page_indicator 페키지를 설치
- postmodal.dart에서 해당 위젯을 추가함

## 변경된 부분
- flutter lint 버전이 변경되었음
- smooth_page_indicator 패키지를 설치함
- photopage.dart에서 pageController추가
- postmodal.dart에서 SmoothPageIndicator추가

## 실행 화면
<img width="397" alt="스크린샷 2023-11-25 오후 3 46 10" src="https://github.com/22nd-Hoondong/Re-Frame/assets/52999093/eb5a500a-5adb-480e-9e4c-e1889f687923">

2023-11-25 07:34 UTC, ldh019 requested changes
바텀 모달 기본 크기를 조금 더 작게 해도 될거 같아요
그리고 모달 안에 말고 바깥쪽 사진 아래에 인디케이터를 놓는 게 더욱 UX가 좋을거 같아용
혹시 가능하다면 인디케이터 크기도 조금 줄여도 좋을거같아여

2023-11-25 08:47 UTC, falconlee236 commented
@ldh019 변경 완료했습니다
<img width="355" alt="스크린샷 2023-11-25 오후 5 46 32" src="https://github.com/22nd-Hoondong/Re-Frame/assets/52999093/4be193dc-1024-4118-b35c-3ead6adcead1">

2023-11-25 09:11 UTC, hnnynh approved these changes
LGTM!!

2023-11-25 17:53 UTC, coffeesigma approved these changes
좋네요

2023-11-26 00:26 UTC, ldh019 approved these changes
조아요 조아 아주 조아

2023-11-26 01:39 UTC, merged