[Feat] 갤러리 페이지에서 꾹 누르기 기능 추가
22nd-Hoondong/Re-Frame pull request #42
Opened 2023-12-05 03:16 UTC by falconlee236

## 개요
Gallery Page에서 사진을 꾹 누르면 나오는 기능을 추가했습니다.

## 작업사항
- Gallery 페이지의 회색 container를 누르면 사진 선택창이 나옴
- 사진이 생기면, 해당 사진을 onTap한다고 해서 사진 선택창이 나오지 않음
- 사진을 삭제하려면 해당 사진을 onLongPress해서 나오는 모달 창을 선택해야함
- 모달창에서 아니오를 누르면 현상 유지
- 모달 창에서 예를 누르면 사진이 사라짐
- 사진을 변경하고 싶다면 위의 과정을 반복하면 됨

## 변경된 부분
- 이미 사진이 있을 때, 다시 사진 선택창에 들어가야 사진을 제거해야하는 문제점 해결
- 이미 사진이 있을 때, 다시 모달 창이 나오는 문제점 해결
- 회색 화면에서 꾹 누르는 gesture 방지

## 실행 화면
![image](https://github.com/22nd-Hoondong/Re-Frame/assets/52999093/c3fb442a-c913-44ae-b1f5-69d24d8c10b5)

2023-12-05 08:37 UTC, ldh019 requested changes
글자색은 검정색이 국룰입니다

2023-12-05 09:15 UTC, hnnynh requested changes
흰색 배경 모달에 폰트 적용한 검은색 글씨 어떨까요

2023-12-05 09:50 UTC, falconlee236 commented
![Uploading image.png…]()
수정 했습니당

2023-12-05 12:29 UTC, ldh019 approved these changes
이쁘다 이뻐

2023-12-05 13:40 UTC, coffeesigma approved these changes
내가말한건..? 동훈이가 괜찮다니까..

2023-12-05 13:40 UTC, coffeesigma commented on lib/Widgets/image_container.dart
> +                        actions: [
혹시 이 부분 아래 버튼들 중앙으로 정렬되어있는게 낫지 않을까요?

2023-12-05 13:55 UTC, falconlee236 commented on lib/Widgets/image_container.dart
> +                        actions: [
수정 안되는줄 알았는데 가운데로 변경이 가능하네요
수정 하겠습니당

2023-12-05 13:55 UTC, falconlee236 commented
@coffeesigma 
![image](https://github.com/22nd-Hoondong/Re-Frame/assets/52999093/0806973b-b673-4da1-937a-307139df1ca2)

이건 어떤가요

2023-12-05 21:51 UTC, coffeesigma approved these changes
너무좋아요

2023-12-06 07:24 UTC, hnnynh approved these changes

2023-12-06 07:25 UTC, merged